on: 
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to main
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install vendors
        run: composer install
      - name: make .env file
        run: cp .env.example .env
      - name: Generate app key secret
        run: php artisab key:generate
