on: 
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to main
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "${{ secrets.SSHKEY_DEV }}"
      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.SSHKEY_DEV }}
          
    
