on: 
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to main
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "${{ secrets.SSHKEY_DEV }}"
      - name: ssh to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.SSHKEY_DEV }}
          port: 22
      - name: cd root folder
        run: cd /var/www/html/cicd/
      - name: show path
        run: pwd
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install vendors
        run: composer install
      - name: make .env file
        run: cp .env.example .env
      - name: Generate app key secret
        run: php artisan key:generate
          

          
    
